/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class MNavigationMesh : TBase
{
  private Dictionary<string, string> _Properties;

  public List<MVector3> Vertices { get; set; }

  public List<int> Triangles { get; set; }

  public Dictionary<string, string> Properties
  {
    get
    {
      return _Properties;
    }
    set
    {
      __isset.Properties = true;
      this._Properties = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool Properties;
  }

  public MNavigationMesh() {
  }

  public MNavigationMesh(List<MVector3> Vertices, List<int> Triangles) : this() {
    this.Vertices = Vertices;
    this.Triangles = Triangles;
  }

  public void Read (TProtocol iprot)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      bool isset_Vertices = false;
      bool isset_Triangles = false;
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.List) {
              {
                Vertices = new List<MVector3>();
                TList _list61 = iprot.ReadListBegin();
                for( int _i62 = 0; _i62 < _list61.Count; ++_i62)
                {
                  MVector3 _elem63;
                  _elem63 = new MVector3();
                  _elem63.Read(iprot);
                  Vertices.Add(_elem63);
                }
                iprot.ReadListEnd();
              }
              isset_Vertices = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.List) {
              {
                Triangles = new List<int>();
                TList _list64 = iprot.ReadListBegin();
                for( int _i65 = 0; _i65 < _list64.Count; ++_i65)
                {
                  int _elem66;
                  _elem66 = iprot.ReadI32();
                  Triangles.Add(_elem66);
                }
                iprot.ReadListEnd();
              }
              isset_Triangles = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.Map) {
              {
                Properties = new Dictionary<string, string>();
                TMap _map67 = iprot.ReadMapBegin();
                for( int _i68 = 0; _i68 < _map67.Count; ++_i68)
                {
                  string _key69;
                  string _val70;
                  _key69 = iprot.ReadString();
                  _val70 = iprot.ReadString();
                  Properties[_key69] = _val70;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
      if (!isset_Vertices)
        throw new TProtocolException(TProtocolException.INVALID_DATA, "required field Vertices not set");
      if (!isset_Triangles)
        throw new TProtocolException(TProtocolException.INVALID_DATA, "required field Triangles not set");
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public void Write(TProtocol oprot) {
    oprot.IncrementRecursionDepth();
    try
    {
      TStruct struc = new TStruct("MNavigationMesh");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Vertices == null)
        throw new TProtocolException(TProtocolException.INVALID_DATA, "required field Vertices not set");
      field.Name = "Vertices";
      field.Type = TType.List;
      field.ID = 1;
      oprot.WriteFieldBegin(field);
      {
        oprot.WriteListBegin(new TList(TType.Struct, Vertices.Count));
        foreach (MVector3 _iter71 in Vertices)
        {
          _iter71.Write(oprot);
        }
        oprot.WriteListEnd();
      }
      oprot.WriteFieldEnd();
      if (Triangles == null)
        throw new TProtocolException(TProtocolException.INVALID_DATA, "required field Triangles not set");
      field.Name = "Triangles";
      field.Type = TType.List;
      field.ID = 2;
      oprot.WriteFieldBegin(field);
      {
        oprot.WriteListBegin(new TList(TType.I32, Triangles.Count));
        foreach (int _iter72 in Triangles)
        {
          oprot.WriteI32(_iter72);
        }
        oprot.WriteListEnd();
      }
      oprot.WriteFieldEnd();
      if (Properties != null && __isset.Properties) {
        field.Name = "Properties";
        field.Type = TType.Map;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.String, TType.String, Properties.Count));
          foreach (string _iter73 in Properties.Keys)
          {
            oprot.WriteString(_iter73);
            oprot.WriteString(Properties[_iter73]);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("MNavigationMesh(");
    __sb.Append(", Vertices: ");
    __sb.Append(Vertices);
    __sb.Append(", Triangles: ");
    __sb.Append(Triangles);
    if (Properties != null && __isset.Properties) {
      __sb.Append(", Properties: ");
      __sb.Append(Properties);
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

